### ISSUE TITLE
Pipes occupying the whole block

### ISSUE THREAD

**Issue by davqvist** [dalapo/FactoryTech#10]
Forge 2494
MC 1.12.2
Factory Tech 1.0.5d

Can you make pipes not occupying the whole block? I mean at least the hitbox, so that you can access machines behind pipes. But also the collision box would be nice so that you don't float in air when you stand on top of them. ( I always confuse collision/hit box, so the terms might be vice versa, I apologize)

**Comment by dalapo** [comment]
Done - also addressed your other issues. Thanks for reporting them!
