### ISSUE TITLE
How does the Potion Mixer work?

### ISSUE THREAD

**Issue by davqvist** [dalapo/FactoryTech#11]
Forge 2494
MC 1.12.2
Factory Tech 1.0.5d

Sorry, not a bug per se, but the book doesn't explain good enough how the Potion Mixer works. So maybe it is bugged, maybe not, I just couldn't get it to work. If it works, maybe add some explanation to the book?

**Comment by dalapo** [comment]
The grey squares in the bottle are input slots. Put 2 or three potions in and it will output a potion with their combined effects.

**Comment by davqvist** [comment]
Oh thanks, there was a big misconception going on. I thoght this lets you automate vanilla potions, not create new potions out of vanilla potions. Sorry, thanks
