### ISSUE TITLE
**Suggestion** CraftTweaker Support

### ISSUE THREAD

**Issue by DaggerTM** [dalapo/FactoryTech#12]
Your mod is amazing, it fits right into my idea for a modpack im developing. But I a person who loves customization, would like to add/and or remove recipes that really captures the use of this mod.

**Comment by dalapo** [comment]
CraftTweaker support is currently in development. However, it will be coming as part of a bigger update, so I haven't got an ETA on when it'll be done. :)

**Comment by davqvist** [comment]
Nice, waiting for it eagerly!

**Comment by dalapo** [comment]
Version 1.1.0, just released, has CraftTweaker support.
