### ISSUE TITLE
[1.12.2-1.10]Console seemingly debug code and errors when starting up

### ISSUE THREAD

**Issue by Lykrast** [dalapo/FactoryTech#14]
Starting with the mod produces a lot of output to the log, most probably debug code, but also some errors (in chronological order in the log) :

https://gist.github.com/Lykrast/2c57c63e1f00697919e076a8b5a54873

https://gist.github.com/Lykrast/2de7c408f7af38ae267177d77db958a3

https://gist.github.com/Lykrast/a6008258fc305fb01a51b5465193d24d

https://gist.github.com/Lykrast/fe754c0ac2aaa0ea0931e836a613dd9f

This was done without any other mod.

**Comment by dalapo** [comment]
Removed the 1st and 4th instances in 1.1.1; the 2nd and 3rd ones are on Forge's end, not mine.
