### ISSUE TITLE
[Suggestion] Add shift-clicking manual item insertion to machines

### ISSUE THREAD

**Issue by Lykrast** [dalapo/FactoryTech#16]
Currently, shift-left-clicking items into the machines doesn't do anything, unlike other machines (such as the vanilla Furnace) where it inserts the items into the correct slots. This makes it a little bit extra tedious inserting input items and replacement parts manually, and thus would be nice if it was implemented.

**Comment by dalapo** [comment]
Added in 1.1.1 - thanks!
