### ISSUE TITLE
[suggestion] Config file instead of hard-coded values

### ISSUE THREAD

**Issue by Fiaegel** [dalapo/FactoryTech#2]
A lot of mods add the same ores as this mod. In order for it to play well in modpacks, an option for turning off ore generation or rebalancing it is required. Other ideas would be options for the "durability" of parts or the amount of outputs, so that modpack devs can rebalance the machines at will, or even crafttweaker support (those things are of lower priority and could come much later down the line but I thought I'd suggest them now)

(If there is a config file and for some reason it didn't generate in my config folder, let me know)

**Comment by jonqrandom** [comment]
i'll second the request for ore config and crafttweaker support, but i also appreciate it's not gonna be a priority at the moment.

**Comment by dalapo** [comment]
Yes, config file support will definitely be coming, but right now JEI integration and major bugfixes are higher priorities.

**Comment by dalapo** [comment]
The latest version adds a simple config file for turning ore generation on/off; config for part consumption will be coming in the future.

**Comment by dalapo** [comment]
Configurable multipliers for part consumption are now in 1.1.6.
