### ISSUE TITLE
[Suggestion] Some UI improvements

### ISSUE THREAD

**Issue by Lykrast** [dalapo/FactoryTech#20]
The following improvements could be nice :

* Put an "Open JEI" button somewhere in the machines that are compatible (this is usually put on the arrow that fills up as the machine processes things)
* Stabilization Table
    * Replace the Current/Energy value of a given Stationary Magnet by a red X when there's no Magnet at this location
    * Change the color of the 0 to red when a Magnet overcharges, to indicate it's not the redstone or lag but that it is overcharged
    * Make the color of the energy value orange/yellow when it approaches critical values (about to overload), although this is debatable
    * Play some sound/particles when a Magnet overcharge, a good placeholder would be the effect Lava does when it turns into Cobblestone
* River Grate
    * Place a red cross on the arrow inside when the location is invalid
    * Add a visual slot for the fishes, they're basically out of the grids right now
* Circuit Scribe
    * Make invalid patterns still saved, so that you can make them over multiple times as you look them up in the manual
    * Add a red cross/green mark icon somewhere to indicate if the pattern is valid or not

**Comment by dalapo** [comment]
1.2 is going to be an aesthetics update, and UI facelifts will be part of that. That said, these are good suggestions!

**Comment by Lykrast** [comment]
Adding to the list : the Tempering Oven doesn't have a visible progress bar on its arrow, which I guess is more a bug than an improvement.

**Comment by dalapo** [comment]
1.1.5 implements all of these except the Circuit Scribe storing patterns (for the reason explained above). Thanks!
