### ISSUE TITLE
Duplicate JEI recipes for the Drill Grinder

### ISSUE THREAD

**Issue by Lykrast** [dalapo/FactoryTech#21]
All recipes that seem to imply grinding Ore into Ground Ore or Ingots into Dust are shown twice in JEI (at least without any other mod). My guess is that one of them is an hardcoded recipe while the other is generated as an oredict one for compatibility, but that's maybe not how it works.

Anyway, here's an example for Iron Dust :
![image](https://user-images.githubusercontent.com/8684850/31734422-ee666960-b43e-11e7-99b6-decea3ffd7d0.png)

**Comment by dalapo** [comment]
Yes, one is hardcoded while the other is Oredict'd. There's supposed to be code to prevent that, but apparently it's not working properly.

**Comment by dalapo** [comment]
Should be fixed in 1.1.5 - let me know if you have any issues.
