### ISSUE TITLE
CraftTweaker Integration

### ISSUE THREAD

**Issue by DrDarkfire** [dalapo/FactoryTech#23]
Hi,
First of all, I love the direction this mod is going. I know that crafttweaker integration appears to have been made, but I am having issues figuring out how to use it. Could you possibly test your integration, and give us templates/sample scripts for the machines?

**Comment by dalapo** [comment]
It should follow the same format as with other mods, but I'll look into it.

**Comment by dalapo** [comment]
The Agitator had a bit of wonky behaviour that I've now fixed; I'll also release an example CraftTweaker file once 1.2 comes out.

**Comment by DrDarkfire** [comment]
Is there an ETA? Not to be pushy about it.

**Comment by DrDarkfire** [comment]
it said for this line: mods.factorytech.ChopSaw.removeRecipe(<minecraft:planks>); 
[INITIALIZATION][CLIENT][ERROR] FactoryTech.zs:1 > No such member: factorytech
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: FactoryTech.zs}: crafttweaker/api/item/IItemStackAny
java.lang.NoClassDefFoundError: crafttweaker/api/item/IItemStackAny
    at FactoryTech.script(FactoryTech.zs:1)

**Comment by dalapo** [comment]
The ETA is when I finish 1.2.

**Comment by dalapo** [comment]
1.1.5 is now out, which addresses these issues. I'll write up a basic guide as soon as possible. Thanks!

**Comment by DrDarkfire** [comment]
thanks for your hard work! I can help you with documentation if you'd like

**Comment by dalapo** [comment]
CraftTweaker documentation is up on CurseForge and the mod's page on the FTB forums.
