### ISSUE TITLE
Placing down mob disassembler places transport rollers

### ISSUE THREAD

**Issue by DrDarkfire** [dalapo/FactoryTech#24]
When I go to place down a mob disassembler, it looks like it is gonna place that down, but then it switches to transport rollers

**Comment by DrDarkfire** [comment]
edit. it was happening earlier, but not anymore.(could just be my instance)

**Comment by dalapo** [comment]
Ah, the law of program bugs: they immediately vanish when you show them to the dev.

**Comment by DrDarkfire** [comment]
Lol. so true. but amazing work on the update as far as I can tell.

**Comment by dalapo** [comment]
Well, seems like this issue has resolved itself, so I'm gonna close it. Glad you're enjoying the mod!

**Comment by DrDarkfire** [comment]
If possible, could you notify me somehow when the documentation on CT support exists
