### ISSUE TITLE
CT support/Config Suggestion

### ISSUE THREAD

**Issue by DrDarkfire** [dalapo/FactoryTech#25]
So regarding the CT support, when I tried to remove all the plank recipes from the chopsaw, all I could do was remove the oak.
My Script:
mods.factorytech.ChopSaw.removeRecipe(<minecraft:planks> * 6);
mods.factorytech.ChopSaw.removeRecipe(<minecraft:planks:1> * 6);
mods.factorytech.ChopSaw.removeRecipe(<minecraft:planks:2> * 6);
mods.factorytech.ChopSaw.removeRecipe(<minecraft:planks:3> * 6);
mods.factorytech.ChopSaw.removeRecipe(<minecraft:planks:4> * 6);
mods.factorytech.ChopSaw.removeRecipe(<minecraft:planks:5> * 6);

So. only the first one worked, but not the rest. This might be something you should look into.

As for config suggestions, I would like to suggest configurable durability for your tiered machine parts, that's something I would like to have control over. Also, if there's a way for you to let us configure what biomes the river grate can work in. Maybe a name change to its ID could be in order?(sluice) Because I know the river part of it is supposed to be the balancing of it, but maybe having other water biomes put in wouldn't hurt.

**Comment by dalapo** [comment]
I think the minecraft:planks:x has to be in angle brackets.

**Comment by DrDarkfire** [comment]
they are. I don't think github let me use those

**Comment by DrDarkfire** [comment]
yes. Just checked my script. they are there it just didn't copy somehow

**Comment by dalapo** [comment]
I'll check the code. As for your config suggestions, I definitely want to add config to control part durability, but I'm still not sure how to implement it nicely since it's two factors (durability and salvaging) for multiple slots for 15 or so machines. Adding a way to whitelist extra biomes for the River Grate shouldn't be too difficult, though.

**Comment by DrDarkfire** [comment]
Possibly it could be an array so it can store two+ values? or a 2D array if you want to use it across parts so it stores all the part values with parts being the durability and parts[0] being salvaging?
if that makes any sense to you

**Comment by DrDarkfire** [comment]
if NuclearCraft or Immersive engineering is open source they probably have good examples of config value usage

**Comment by DrDarkfire** [comment]
Also. Trying to get things 100% automated in your mod is fun and challenging :P

**Comment by dalapo** [comment]
I feel like the most viable way would be to have an enum with one entry for each machine, where each entry has an array of size Nx2 (N being the number of different parts it has).

**Comment by DrDarkfire** [comment]
true. I feel like people would want the parts to have durability based off of the machine. For example: maybe I think the drill should dull faster in the automatic miner compared to the ore driller.

**Comment by dalapo** [comment]
Technically, it does already (minimum 7 operations in the autominer and 8 in the grinder), but I get what you mean.

**Comment by DrDarkfire** [comment]
All I have to say is that the CT support testing should be the highest priority. Part durabilities aren't our{pack developers) biggest concerns. Easiest configs to add should be second, and then all the other configs that basically let us pack devs tear your mod apart should be later on the list.

These are just comments coming from the views of a pack developer.

**Comment by dalapo** [comment]
I think I fixed the CraftTweaker support (complete with a newfound disdain of ConcurrentModificationExceptions); there is a bunch of other stuff I'd like to do before the next update, if you can stand to wait.

**Comment by DrDarkfire** [comment]
could I possibly get this snapshot version so I can test it for myself?

**Comment by dalapo** [comment]
I'd rather you wait for the update, but thanks for offering. :)

**Comment by DrDarkfire** [comment]
Could I get an idea of what will(should) be in the next update?

**Comment by dalapo** [comment]
The CraftTweaker fix, config additions, and an easter egg.

**Comment by dalapo** [comment]
1.1.6, with these changes, is currently going through CurseForge.

**Comment by DrDarkfire** [comment]
neato

**Comment by DrDarkfire** [comment]
1.1.6 or 1.1.5b?

**Comment by DrDarkfire** [comment]
nevermind. saw the 1.1.5b update date

**Comment by DrDarkfire** [comment]
Have looked at the update. The CT was most definitely fixed, and the configs left me drooling over my keyboard.

**Comment by dalapo** [comment]
An important note is that setting the lifespan multiplier to 0 won't make machines consume one part per operation - it only sets the minimum operations of that part to 0, after which consumption is governed by RNG.

**Comment by DrDarkfire** [comment]
So. lifespan is the base amount of uses a part has, and salvage is the chance it will take/not take away a durability

**Comment by dalapo** [comment]
Salvage chance is the probability that when a part breaks, it will give back a broken part that can be reclaimed.

I have plans to further expand on the config.

**Comment by DrDarkfire** [comment]
ahhh ok. btw is it possible the configs could be changed so that we know what part is part 0, part 1, part 2. it looks like you went the uber easy way out on it, and when I have configs open I'm not staring down the game.
