### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash(1.12.2) crash on launch

### ISSUE THREAD

**Issue by SDUBZ** [dalapo/FactoryTech#27]
Forge:1.12.2-2517
Factory tech:1.12.2-1.1.6

Crash Report:
[crash-2017-10-31_17.55.23-client.txt](https://github.com/dalapo/FactoryTech/files/1429800/crash-2017-10-31_17.55.23-client.txt)

**Comment by dalapo** [comment]
Fixed for 1.1.6b - thanks!

**Comment by SDUBZ** [comment]
no thank you for fixing :D
