### ISSUE TITLE
Automatic Crafter crashes game 1.1.6b

### ISSUE THREAD

**Issue by DrDarkfire** [dalapo/FactoryTech#28]
Crafter causes crash. This time I actually repeated the crash multiple times in different worlds.

[crash-2017-11-02_18.22.54-client.txt](https://github.com/dalapo/FactoryTech/files/1439974/crash-2017-11-02_18.22.54-client.txt)

[crash-2017-11-02_18.22.54-client.txt](https://github.com/dalapo/FactoryTech/files/1439973/crash-2017-11-02_18.22.54-client.txt)

**Comment by DrDarkfire** [comment]
If possible, could you start leaving older versions on curse? This is something other devs do just in case something borks real bad so the players can work with the older version while the new one is being fixed and it doesn't produce a hold up

**Comment by dalapo** [comment]
I've been archiving them to reduce clutter, but I understand where you're coming from. Fixed the crash and uploaded it as 1.1.6c.
