### ISSUE TITLE
Stack Mover dupe bug 1.1.6

### ISSUE THREAD

**Issue by DrDarkfire** [dalapo/FactoryTech#29]
I have found that the stack movers dupe items if they are in a crate and then you apply a redstone signal to the stack movers. could effectively make a rapid firing pulse and get 1000's of items a minute.

- Derpfire

**Comment by dalapo** [comment]
Could not reproduce. What's your exact setup? Which type of Stack Mover are you using? Are you dropping items into the world or inserting them into another inventory?

**Comment by DrDarkfire** [comment]
Dropping them in world. gonna submit a video to you

**Comment by DrDarkfire** [comment]
kidding. it doesn't support video. here's a screenshot of the setup
![2017-11-05_10 00 40](https://user-images.githubusercontent.com/20916594/32415993-405d03da-c210-11e7-9555-a793a2bdcada.png)

**Comment by dalapo** [comment]
Well, that's a rather embarrassing bug! Fixed and will upload soon as
1.1.6d. Thanks!

**Comment by DrDarkfire** [comment]
also. I'm streaming your mod at https://twitch.tv/dr_darkfire
