### ISSUE TITLE
[suggestion] QoL improvements to the guide

### ISSUE THREAD

**Issue by Fiaegel** [dalapo/FactoryTech#3]
The mod is based a lot around the player using the in-game guide as he progresses. But it gets annoying having to click until you find what you're looking for each time. So consider either of those features: 
1. Items in each category are in a list for easier access, once you are in a page for a specific item, you can also use the arrows like you can with the current functionality.
2. The page you are currently reading will be there when you close and reopen the guide, instead of going back to the home page.
3. A search bar

**Comment by dalapo** [comment]
Done; the guide now remembers what page you closed it on.
