### ISSUE TITLE
[1.12.2] Broken Mob Disassembler

### ISSUE THREAD

**Issue by EmosewaGamer** [dalapo/FactoryTech#34]
The Mob Disassembler is invisible when placed:
![image](https://user-images.githubusercontent.com/25333164/34007549-83bf1e22-e102-11e7-85f8-798065fa29d0.png)
 And causes the following crash when broken:
https://pastebin.com/cQJ3fyx7

**Comment by dalapo** [comment]
Was able to duplicate the invisibility but not the crash. Regardless, should be fixed now.
