### ISSUE TITLE
[1.12.2] Freeze When Placing Extraction Pump

### ISSUE THREAD

**Issue by EmosewaGamer** [dalapo/FactoryTech#35]
When placing an extraction pump, my game freezes as it's about to crash. It doesn't manage to crash, but in the log I have:
https://pastebin.com/9naNR2Mt

**Comment by dalapo** [comment]
Could not reproduce. What version of FT/Forge are you using?

**Comment by EmosewaGamer** [comment]
14.23.1.2562 I guess Ima try the latest one.

**Comment by EmosewaGamer** [comment]
Welp, it still happens to me. It's just the worst when the modder can't reproduce it. I'll see if others can.

**Comment by dalapo** [comment]
What are you trying to use it with? Might be a mod interface issue.

**Comment by EmosewaGamer** [comment]
The Crucible, But yet, no matter where I place it, it causes a crash.

**Comment by dalapo** [comment]
How long has this been happening for you?

**Comment by EmosewaGamer** [comment]
Ok, this seems to not occur anymore.
