### ISSUE TITLE
[1.12.2] Crash When Breaking Core Charger

### ISSUE THREAD

**Issue by EmosewaGamer** [dalapo/FactoryTech#36]
Just as the title says, when breaking a Core Charger, I get the following crash:
https://pastebin.com/3gLXtw6S

 I believe that you should make sure that no other block causes this crash when broken.

**Comment by tyler489** [comment]
Pretty sure thats caused by foamfix. Most" Cannot get property PropertyEnum{name=facing, clazz=class " crashes are at least in my experiences

**Comment by EmosewaGamer** [comment]
You were correct. Updating it fixed this issue, but only this issue.
