### ISSUE TITLE
[1.12.2] Crash When Going Through Pages Too Quickly

### ISSUE THREAD

**Issue by EmosewaGamer** [dalapo/FactoryTech#37]
So I pressed the ">" in the Blueprint Collection too fast and got the following crash:
https://pastebin.com/rVPcW8yX

**Comment by dalapo** [comment]
I couldn't reproduce this or any of the other bugs you reported.

**Comment by EmosewaGamer** [comment]
Ok, it now seems to happen after the Metal Cutting Machine. Why did it not happen the first time i went through the book, I have no idea.

**Comment by EmosewaGamer** [comment]
Ok, I figured out why this occurs: With CraftTweaker I have removed the AutoCrafting Unit's recipe (and hidden it from JEI which probably doesn't matter). That's why when I get to its page the client crashes.

**Comment by dalapo** [comment]
I'll add a check so that it'll just hide a recipe if it doesn't exist.
