### ISSUE TITLE
[1.0.2] single quartz plate returns from chop saw

### ISSUE THREAD

**Issue by jonqrandom** [dalapo/FactoryTech#4]
the manual states the chop saw should return four quartz plates for one quartz block, but it only returns one plate. this is on minecraft 1.12.2 with forge 14.23.0.2493, and only factory tech 1.0.2 installed. same applies for plain, chiselled and pillar quartz.

**Comment by jonqrandom** [comment]
perhaps i'm confused. why did you silently close this? have i not provided information you need?

**Comment by dalapo** [comment]
It's fixed for the next update, which will also have JEI integration.

**Comment by jonqrandom** [comment]
ah, okies, sorry, i was worried i'd done something wrong or offended you or something! anyways, thank you for the good news! :)
