### ISSUE TITLE
Crash when placing the Drill Grinder, and when viewing its page in the Blueprint Collection

### ISSUE THREAD

**Issue by Kevun1** [dalapo/FactoryTech#42]
Forge v2571
Factory Tech v1.3a

When I try and place the Drill Grinder down, it crashes the game.

Log: https://pastebin.com/PZB1Qs5m

Probably related, I also crash whenever whenever I try to open the 'Drill Grinder' page, under 'Machine Info' in the Blueprint Collection

Log: https://pastebin.com/YumwebeJ

**Comment by Kevun1** [comment]
The same applies for the Seed Disperser

**Comment by dalapo** [comment]
Fixed and uploaded as 1.3b. Looks like a few machines slipped through the cracks when the part handling code was rewritten for 1.3. Thanks!
