### ISSUE TITLE
Blueprint collection book doesn't show which side to put parts into each machine

### ISSUE THREAD

**Issue by Frefreak** [dalapo/FactoryTech#45]
Hi, the recent commits removed the "parts required" string from machine.txt (seems like to dynamically show the detailed parts info?) , but the side info is missing. Here is what it looks like now:

![image](https://user-images.githubusercontent.com/7122156/35179174-70674a5e-fdcf-11e7-95bb-7702a90212af.png)

**Comment by dalapo** [comment]
Now shown as part of the Magnifying Glass info.
