### ISSUE TITLE
Conveyors delete items

### ISSUE THREAD

**Issue by kitsu** [dalapo/FactoryTech#47]
MC 1.12.2
Forge 14.23.1.2587
FactoryTech 1.3.1 (displays as 1.1.6b in MultiMC)
[Expanded Industry](https://minecraft.curseforge.com/projects/expanded-industry?gameCategorySlug=mc-mods&projectID=232258) 4.0.0a

As a test prior to setting up my first processing lines using FT conveyors I placed one over an Expanded Industry wooden hopper with another feeding it. After throwing two stacks of cobblestone onto the first conveyor they all traveled to the hoppered conveyor and disappeared. The first problem is they shouldn't have, wooden hoppers only hold 5x16, the remainder should have rolled off the end.
Even worse though when I looked in the hopper there was **only one stack of 16 cobble!** The conveyor _deleted_ the overflow items.

I then tested the same setup using Immersive Engineering conveyor and dropping conveyor in the same setup, and all the items ended up where they belong. All slots filled with 16 and the overflow on the ground.

Great job on the mod so far, I think it is one of the most interesting ideas in a long time!

**Comment by dalapo** [comment]
My conveyors only move items as entities, so the result should be identical to what would happen if you toss them in yourself. Are you using an Insertion Hatch or something?

**Comment by dalapo** [comment]
Just tested it myself. Installed the mod, placed down a Wooden Hopper, and tossed a full stack of Cobble in; the first slot filled to 16 and the rest vanished. Breaking the Hopper gave inconsistent results, making some or all of it reappear.

Basically, this is an Expanded Industry bug, not a Factory Tech one.

**Comment by kitsu** [comment]
Agreed, opened an issue with Expanded Industry.
