### ISSUE TITLE
[1.12.2]GUI errors on server

### ISSUE THREAD

**Issue by pennyvise1** [dalapo/FactoryTech#49]
https://pastebin.com/f7GCgz32

Modern Skyblock 3 modpack

This was the console spam.  I was trying to use the grindstone and when I had the GUI open my inventory would desync and random items would appeared to be duped, couldn't insert into any machine, couldn't pipe into the machine sides using hoppers. Single player was fine.

**Comment by dalapo** [comment]
I believe I've found the source of this; can't reliably test it but I'll upload a fix tonight. Keeping this open until then.

**Comment by pennyvise1** [comment]
I'll test for you as soon as i see the update and let you know how it goes before I unplug tonight

**Comment by dalapo** [comment]
There's a couple more things I'm in the middle of that I need to finish before updating so might have to wait till tomorrow, but thanks!

**Comment by pennyvise1** [comment]
Tested quick this morning, I'll do a full run through today but looks like you got it, much appreciated man

**Comment by pennyvise1** [comment]
Everything worked great until i got to the tempering oven, my sawblades started disappearing when they were done tempering, then I broke the block and my client crashed, server stayed up, ill post logs after  stream

**Comment by dalapo** [comment]
Hmm... that's a TESR error. If you want a temporary fix, go into the config file and turn off client-side machine animations. I'll look into it this evening or tomorrow.

**Comment by dalapo** [comment]
Should be all fixed now.
