### ISSUE TITLE
Lift Fans not pushing items into lift recievers like they used to

### ISSUE THREAD

**Issue by Raetac** [dalapo/FactoryTech#50]
Running 1.3.6

**Comment by dalapo** [comment]
Fixed in 1.3.6b :)

**Comment by kitsu** [comment]
Are you sure?

Using 1.3.6b lifted items seem to hang up on anything near by.
I though maybe if I put your roller conveyors over the fan items would only be lifted when over the center, but they block the lifting (but not the particles!).

It seems like a neat form of vertical transport, but I'm going to switch to hopper-ducts for now.

Everything else seems to be working really smoothly, working on setting up my first mineral processing factory.

**Comment by dalapo** [comment]
The reason fan lifts don't work in your scenario is that they're being blocked by the conveyors.
