### ISSUE TITLE
MSB3 crash breaking electric furnace

### ISSUE THREAD

**Issue by pennyvise1** [dalapo/FactoryTech#51]
https://pastebin.com/Mb5ePWe3

Getting the same crash on the electric furnace, which is weird because i had to issues breaking it a couple days ago

**Comment by dalapo** [comment]
From the crash log you're still running 1.3.6 - it's fixed in 1.3.6b.

**Comment by pennyvise1** [comment]
Oh gotcha, I updated and it must have put the old one back in, sorry
