### ISSUE TITLE
Basic Gears can't be inserted into Autocrafting Units through an Input Harch.

### ISSUE THREAD

**Issue by ncaycedo** [dalapo/FactoryTech#54]
I tested it with a Pulse Piston and it isn't working either. The hopperhock from Botania seems to work fine though.

Steps to reproduce:
1. Place down autocrafting unit.
2. Make sure the part input is on the side facing me with a monkey wrench.
3. Put an input hatch next to that face.
4. Place down some transport rollers leading up to the hatch.
5. Throw some basic gears on the rollers.
6. The gears get stuck at the hatch on the rollers and don't get inserted into the machine.

You can just skip the transport rollers and the result will be the same. Some people on the Modern Skyblock 3 discord channel also tried it, I'm guessing they're using the newest version, I am not.

Minecraft version: 1.12.2
Forge version: 14.23.1.2608
Factory Tech version: 1.3.5

**Comment by dalapo** [comment]
Found the issue - unfortunately I'm in the middle of adding some other things right now but it shouldn't be too hard to fix.

**Comment by dalapo** [comment]
Fixed in 1.3.6d.
