### ISSUE TITLE
Sharpening Tools only damages them

### ISSUE THREAD

**Issue by davqvist** [dalapo/FactoryTech#6]
Forge 2494
MC 1.12.2
Factory Tech 1.0.5d

Sharpening Tools supposedly - according to the in game book - gives them Efficiency/Sharpness, but instead just damages them without applying the enchantment.

**Comment by dalapo** [comment]
This is very odd. I confirmed that this is the case, but I have changed nothing about the Grindstone since I last tested it (and it worked properly).
