### ISSUE TITLE
Actually Additions not unlooking

### ISSUE THREAD

**Issue by Khalep** [dalapo/FactoryTech#60]
In my Version 3.1.5.3 Actually Additions wont unlock even though i completed all progression Quest up to A Basic factory. Heavy Machinery and Life in the Forest is also Completed. A True Blacksmith is half complet becaus i don't yet have acces to The Wither for a Beacon. 
The Power of the Stars is unlocked but without Actually Additions i can't craft Rock CRystal Ore or Floating Crystal. 
Any ideas?

**Comment by dalapo** [comment]
This is a Modern Skyblock 3 issue, not a Factory Tech one.
