### ISSUE TITLE
Machine Output Inventories Don't respect Stack-size Limits of Parts.

### ISSUE THREAD

**Issue by TeetoKaziim** [dalapo/FactoryTech#61]
In FactoryTech 1.3.7:

Parts normally only stack to 4. But my Metal Cutter and Grindstone, if I fill them with material and let them produce parts, will fill with stacks of 64 parts.

Mod's been lotsa fun :3 Thanks so much.

**Comment by dalapo** [comment]
Should be fixed in 1.3.8. Thanks!

**Comment by dalapo** [comment]
Forgot to close this when I released 1.3.8, it seems.
