### ISSUE TITLE
A config option to use another mod's metals

### ISSUE THREAD

**Issue by PandaBoy444** [dalapo/FactoryTech#67]
It would be nice to be able to unify and it's probably not too hard

**Comment by dalapo** [comment]
What for? Is support for this not already implemented? Or are you talking about smelting my dusts to get a different mod's metals?

**Comment by PandaBoy444** [comment]
Sorry, I wasn't clear, it was 5 am when I wrote this issue. Let me restart, can you add an option to use other outputs for the Rivergate? I guess that ties into #65, which would solve my problem.
