### ISSUE TITLE
[1.4] Gold Wire Motor has invalid recipe

### ISSUE THREAD

**Issue by ErdrickXLII** [dalapo/FactoryTech#76]
The recipe for the Gold Wire Motor requires a non-existent machine part instead of a Gold Wire.

**Comment by dalapo** [comment]
Shoot, must have forgotten that one when I overhauled the parts again.

**Comment by EmosewaPixel** [comment]
As well as the Stone Blade... probably a more significant one
![image](https://user-images.githubusercontent.com/25333164/40443774-a25f7a32-5ec7-11e8-95c8-94fa5f740dd1.png)

**Comment by dalapo** [comment]
Fixed in 1.5.
