### ISSUE TITLE
Pulse piston stuck on world, can't be removed even with setblock

### ISSUE THREAD

**Issue by BlakeTech** [dalapo/FactoryTech#90]
Used the pulse piston in MSB3, and now the pulse piston is in a state of semi-existance. It shows up as a block with the visual graphics, but no GUI, waiting on server error message, being immortally respawning once broken, and setblock does nothing. Restarted server too. Persisted. What to do to exorcise this lingering block-spirit?

**Comment by pgr4567** [comment]
I have the same issue here. It seems like @dalapo isn´t active on github anymore, is this true? Is the support on this mod discontinued?

**Comment by Nabushika** [comment]
Same here

**Comment by Nabushika** [comment]
@JasperTecHK @pgr4567 You can remove the block if you open the world in singleplayer.

It seems if you're playing Modern Skyblock 3, it includes the wrong version of the mod (1.6.6a). I managed to fix this on my server by updating server and clients to version 1.6.C, now pulse pistons seem to be working fine.

**Comment by BlakeTech** [comment]
@Nabushika While I appreciate the help to get it fixed, this is a year-old thread, I highly doubt either one of us is still playing this modpack. Regardless, it (I'll take your word on it) is a solution, so I say, issue resolved?
